import { useState } from 'react';
import { Alert, Input, Modal, Select } from 'antd';
import type { Candidate, State } from '../shared/contracts';
import type { RunCommand } from './bridge';
import { AccountSelector, Field } from './primitives';

export function CandidateEditor({ state, run, busy, close, candidate, accountId }: { readonly state: State; readonly run: RunCommand; readonly busy: boolean; readonly close: () => void; readonly candidate?: Candidate; readonly accountId: string }) {
  const [value, setValue] = useState<Candidate>(candidate ?? { id: '', accountId, jobId: '', name: '', resume: '', message: '', draft: '', mode: 'draft', updatedAt: '', source: 'manual' });
  const platform = value.source === 'platform';
  return <Modal title={platform ? '关联岗位与补充资料' : candidate ? '编辑手工资料' : '录入手工资料'} open onCancel={close} okText="保存资料" cancelText="取消" confirmLoading={busy} okButtonProps={{ disabled: !value.accountId || !value.jobId || !value.name.trim() }} onOk={() => { void run({ type: 'saveCandidate', value: { ...value, id: value.id || crypto.randomUUID(), name: value.name.trim(), updatedAt: new Date().toISOString() } }).then(ok => { if (ok) close(); }); }}><div className="stack"><Alert type="info" showIcon message={platform ? '请根据平台岗位提示手动关联本账号岗位。补充经历不会改变资料的智联来源。' : '此处保存你手工提供的候选人资料，不代表已同步智联会话。'} /><div className="form-grid"><Field label="所属账号" htmlFor="manual-account">{platform ? <Input id="manual-account" value={state.accounts.find(account => account.id === value.accountId)?.name || value.accountId} readOnly /> : <AccountSelector id="manual-account" accounts={state.accounts} value={value.accountId} onChange={id => setValue({ ...value, accountId: id, jobId: '' })} />}</Field><Field label="招聘岗位" htmlFor="manual-job" help={platform ? `平台岗位：${value.platformJobTitle || '未提供'}，请自行确认对应岗位。` : '请选择本资料对应的招聘岗位。'}><Select id="manual-job" value={value.jobId || null} placeholder="选择岗位" options={state.jobs.filter(job => job.accountId === value.accountId).map(job => ({ value: job.id, label: job.title }))} onChange={id => setValue({ ...value, jobId: id })} /></Field></div><Field label="候选人称呼" htmlFor="manual-name"><Input id="manual-name" readOnly={platform} maxLength={100} value={value.name} onChange={event => setValue({ ...value, name: event.target.value })} /></Field><Field label="简历或相关经历（手工录入）" htmlFor="manual-resume"><Input.TextArea id="manual-resume" rows={5} maxLength={20000} value={value.resume} onChange={event => setValue({ ...value, resume: event.target.value })} placeholder="粘贴已获准处理的简历文字或岗位相关经历" /></Field><Field label={platform ? '会话最近消息摘要（智联同步，只读）' : '候选人消息（手工录入）'} htmlFor="manual-message"><Input.TextArea id="manual-message" rows={3} readOnly={platform} maxLength={12000} value={value.message} onChange={event => setValue({ ...value, message: event.target.value })} placeholder="可选：粘贴需要回复的消息" /></Field></div></Modal>;
}
