import { useState } from 'react';
import { Button, Input, Modal, Select } from 'antd';
import { Plus } from 'lucide-react';
import type { Rule, State, Template } from '../shared/contracts';
import type { RunCommand } from './bridge';
import { Field } from './primitives';

export function Templates({ state, run, busy, close }: { readonly state: State; readonly run: RunCommand; readonly busy: boolean; readonly close: () => void }) {
  const [value, setValue] = useState<Template>({ id: '', name: '', text: '' });
  return <Modal title="招呼语模板" open onCancel={close} okText="保存模板" cancelText="关闭" confirmLoading={busy} okButtonProps={{ disabled: !value.name.trim() || !value.text.trim() }} onOk={() => { void run({ type: 'saveTemplate', value: { ...value, id: value.id || crypto.randomUUID(), name: value.name.trim(), text: value.text.trim() } }).then(ok => { if (ok) close(); }); }}><div className="stack"><div className="cluster"><Select className="template-select" aria-label="选择已有模板" value={value.id || null} placeholder="选择已有模板进行编辑" options={state.templates.map(template => ({ value: template.id, label: template.name }))} onChange={id => { const template = state.templates.find(item => item.id === id); if (template) setValue(template); }} /><Button icon={<Plus size={14} />} onClick={() => setValue({ id: '', name: '', text: '' })}>新建</Button></div><Field label="模板名称" htmlFor="template-name"><Input id="template-name" value={value.name} maxLength={80} onChange={event => setValue({ ...value, name: event.target.value })} /></Field><Field label="招呼语正文" htmlFor="template-text" help="可用变量：{岗位}、{称呼}。请勿填写未经确认的薪资与待遇承诺。"><Input.TextArea id="template-text" rows={6} maxLength={2000} showCount value={value.text} onChange={event => setValue({ ...value, text: event.target.value })} placeholder="你好，我们正在招聘{岗位}，想了解你近期是否考虑新的工作机会？" /></Field></div></Modal>;
}
export function Rules({ state, run, busy, close, initialJob = '' }: { readonly state: State; readonly run: RunCommand; readonly busy: boolean; readonly close: () => void; readonly initialJob?: string }) {
  const empty: Rule = { jobId: initialJob, facts: '', faq: '', questions: '', skills: '' };
  const [value, setValue] = useState<Rule>(() => state.rules.find(rule => rule.jobId === initialJob) ?? empty);
  return <Modal title="岗位 AI 设置" open onCancel={close} okText="保存规则" cancelText="取消" confirmLoading={busy} okButtonProps={{ disabled: !value.jobId }} onOk={() => { void run({ type: 'saveRule', value }).then(ok => { if (ok) close(); }); }}><div className="stack"><Field label="招聘岗位" htmlFor="rules-job"><Select id="rules-job" value={value.jobId || null} placeholder="请选择岗位" options={state.jobs.map(job => ({ value: job.id, label: `${job.title} · ${state.accounts.find(account => account.id === job.accountId)?.name ?? ''}` }))} onChange={jobId => setValue(state.rules.find(rule => rule.jobId === jobId) ?? { ...empty, jobId })} /></Field><Field label="岗位事实" htmlFor="rules-facts" help="填写岗位特有的职责、地点、工时和待遇。公司通用信息在左侧“公司与岗位知识库”维护。"><Input.TextArea id="rules-facts" rows={4} maxLength={12000} value={value.facts} onChange={event => setValue({ ...value, facts: event.target.value })} /></Field><Field label="常见问题与标准回答" htmlFor="rules-faq"><Input.TextArea id="rules-faq" rows={3} maxLength={12000} value={value.faq} onChange={event => setValue({ ...value, faq: event.target.value })} /></Field><Field label="需要了解的问题" htmlFor="rules-questions"><Input.TextArea id="rules-questions" rows={3} maxLength={4000} value={value.questions} onChange={event => setValue({ ...value, questions: event.target.value })} /></Field><Field label="岗位相关技能" htmlFor="rules-skills"><Input id="rules-skills" maxLength={2000} value={value.skills} onChange={event => setValue({ ...value, skills: event.target.value })} placeholder="用于辅助理解岗位，不自动决定录用" /></Field></div></Modal>;
}
