import { useState } from 'react';
import { Alert, Button, Input, InputNumber, Radio, Select } from 'antd';
import { Pause, Play, RefreshCw, Square } from 'lucide-react';
import type { State } from '../shared/contracts';
import type { RunCommand } from './bridge';
import { formatTime } from './bridge';
import { AccountSelector, EmptyState, Field, PageHeader, Status, TaskSection } from './primitives';

export function Tasks({ state, run, busy, openTemplates }: { readonly state: State; readonly run: RunCommand; readonly busy: boolean; readonly openTemplates: () => void }) {
  const [accountId, setAccountId] = useState('');
  const [jobId, setJobId] = useState('');
  const [templateId, setTemplateId] = useState('');
  const [skills, setSkills] = useState('');
  const [intervalMinutes, setIntervalMinutes] = useState(5);
  const [limit, setLimit] = useState(1);
  const [mode, setMode] = useState<'draft' | 'send'>('draft');
  const template = state.templates.find(item => item.id === templateId);
  const candidates = state.candidates.filter(item => item.accountId === accountId && item.jobId === jobId);
  const account = state.accounts.find(item => item.id === accountId);
  const canStart = account?.status === 'connected' && jobId && templateId && !busy && candidates.length > 0 && (mode === 'draft' || state.capabilities.greeting);
  return <main className="page"><PageHeader title="自动打招呼" description="先预演话术和筛选结果，再开展有记录的招聘沟通。" actions={<Button onClick={openTemplates}>管理招呼语</Button>} /><div className="task-layout"><div className="stack">
    <TaskSection number="01" title="账号与职位" actions={<Button size="small" icon={<RefreshCw size={14} />} disabled={!accountId || busy} onClick={() => void run({ type: 'syncJobs', id: accountId })}>刷新岗位</Button>}><div className="form-grid"><Field label="智联账号" htmlFor="task-account"><AccountSelector id="task-account" accounts={state.accounts} value={accountId} onChange={id => { setAccountId(id); setJobId(''); setSkills(''); }} /></Field><Field label="招聘岗位" htmlFor="task-job"><Select id="task-job" value={jobId || null} placeholder="请选择招聘岗位" disabled={!accountId} options={state.jobs.filter(job => job.accountId === accountId).map(job => ({ value: job.id, label: job.title }))} onChange={setJobId} notFoundContent="暂无岗位，请先同步" /></Field></div></TaskSection>
    <TaskSection number="02" title="推荐人才筛选"><div className="form-grid"><Field label="必备技能（本地文字匹配）" htmlFor="task-skills" help="多个技能用逗号分隔，仅匹配手工简历中的文字；不自动决定录用。"><Input id="task-skills" maxLength={2000} value={skills} onChange={event => setSkills(event.target.value)} placeholder="例如：销售、客户维护" /></Field><Field label="意向城市" htmlFor="task-city" help="当前资料没有结构化城市字段，暂不可用于筛选。"><Input id="task-city" disabled placeholder="待接入平台筛选能力" /></Field></div><p className="muted">当前范围：本岗位已录入的 {candidates.length} 份手工资料。平台推荐人才尚未接入。</p></TaskSection>
    <TaskSection number="03" title="任务设置"><div className="form-grid"><Field label="打招呼语" htmlFor="task-template"><Select id="task-template" value={templateId || null} placeholder="请选择招呼语模板" options={state.templates.map(item => ({ value: item.id, label: item.name }))} onChange={setTemplateId} notFoundContent="请先创建招呼语模板" /></Field><Field label="执行模式"><Radio.Group value={mode} onChange={event => setMode(event.target.value === 'send' ? 'send' : 'draft')}><Radio value="draft">草稿预演</Radio><Radio value="send" disabled={!state.capabilities.greeting}>平台发送</Radio></Radio.Group></Field><Field label="处理间隔（分钟）" htmlFor="task-interval"><InputNumber id="task-interval" min={1} max={1440} precision={0} value={intervalMinutes} onChange={value => setIntervalMinutes(value ?? 5)} /></Field><Field label="计划人数" htmlFor="task-limit"><InputNumber id="task-limit" min={1} max={1000} precision={0} value={limit} onChange={value => setLimit(value ?? 1)} /></Field></div>{template && <div className="template-preview"><small>模板预览</small><p>{template.text}</p></div>}<Alert showIcon type="info" message="草稿预演只在本地生成招呼语，不向候选人发送。平台发送待接入验证。" /><div className="form-actions"><Button type="primary" icon={<Play size={15} />} disabled={!canStart} loading={busy} onClick={() => void run({ type: 'createTask', value: { accountId, jobId, templateId, intervalMinutes, limit, skills, city: '', mode } })}>启动草稿任务</Button></div></TaskSection>
  </div><div className="task-status-column"><TaskSection number="04" title="本地任务状态">{state.tasks.length === 0 ? <EmptyState title="尚无招聘任务" description="选择账号、岗位和招呼语后，即可启动草稿任务。" /> : <div className="stack">{state.tasks.map(task => <article className="task-card" key={task.id}><div className="cluster"><h3>{state.jobs.find(job => job.id === task.jobId)?.title || '招聘任务'}</h3><Status value={task.status} /></div><small>{state.accounts.find(item => item.id === task.accountId)?.name} · {task.mode === 'draft' ? '草稿预演' : '平台发送'}</small><div className="task-counts"><span>已处理<strong>{task.processed}</strong></span><span>已生成<strong>{task.drafted}</strong></span><span>已发送<strong>{task.sent}</strong></span><span>跳过<strong>{task.skipped}</strong></span></div><p className="muted">计划 {task.limit} 人 · 间隔 {task.intervalMinutes} 分钟</p>{task.reason && <p className="task-reason">{task.reason}</p>}{task.status === 'running' && task.nextAt && <small>下次处理：{formatTime(task.nextAt)}</small>}<div className="cluster task-controls">{task.status === 'running' && <Button size="small" icon={<Pause size={13} />} disabled={busy} onClick={() => void run({ type: 'taskAction', id: task.id, action: 'pause' })}>暂停</Button>}{task.status === 'paused' && <Button size="small" icon={<Play size={13} />} disabled={busy} onClick={() => void run({ type: 'taskAction', id: task.id, action: 'resume' })}>继续</Button>}{['running', 'paused', 'blocked'].includes(task.status) && <Button size="small" danger icon={<Square size={12} />} disabled={busy} onClick={() => void run({ type: 'taskAction', id: task.id, action: 'stop' })}>停止</Button>}</div></article>)}</div>}</TaskSection><p className="task-footnote">页面切换不影响正在运行的任务。退出软件后任务停止，下次启动需手动恢复。</p></div></div></main>;
}
